site_name: Advance JS Study Notes
site_url: http://k8s-study.shams-nahid.com/
site_description: K8s Study notes
site_author: Shams Nahid

repo_url: https://github.com/bmshamsnahid/my-k8s-study
edit_uri: ''

extra_css:
  - css/extra.css

copyright: Copyright &copy; 2021 <a href="https://shams-nahid.com/">Shams Nahid</a>.
